ALTER TABLE "developer_profiles_educations" DROP CONSTRAINT "developer_profiles_educations_background_id_developer_profiles_backgrounds_id_fk";
--> statement-breakpoint
ALTER TABLE "developer_profiles_languages" DROP CONSTRAINT "developer_profiles_languages_background_id_developer_profiles_backgrounds_id_fk";
--> statement-breakpoint
ALTER TABLE "developer_profiles_skills" DROP CONSTRAINT "developer_profiles_skills_background_id_developer_profiles_backgrounds_id_fk";
