import {
  assignmentPermissions,
  assignments,
  cohorts,
  developerProfiles,
  projectPermissions,
  projects,
} from "./permissions";
import { MenuPermissions } from "./permissions/menu";

export const rolesPermissions = {
  guest: new Set([
    developerProfiles.getBackgroundByDeveloperProfileId,
    developerProfiles.getAllSkills,
    developerProfiles.getAllLanguages,
    developerProfiles.getAllEducations,
    projects.getAll,
    developerProfiles.getAll,
    developerProfiles.getDeveloperProfileByIdentityId,
    developerProfiles.getDeveloperById,
    developerProfiles.getHighlightedDeveloperProfileIds,
    assignments.getAssignmentsByCohortId,
    assignments.getAssignmentBySlug,
  ]),
  admin: new Set([
    ...Object.values(projects),
    ...Object.values(developerProfiles),
    ...Object.values(assignments),
    ...Object.values(cohorts),
  ]),
  developer: new Set([
    cohorts.getCohortIdByIdentityId,
    developerProfiles.addBackground,
    developerProfiles.getAllEducations,
    developerProfiles.getAllLanguages,
    developerProfiles.getAllSkills,
    developerProfiles.getBackgroundByDeveloperProfileId,
    developerProfiles.updateBackground,
    developerProfiles.searchDeveloperProfileIds,
    developerProfiles.searchDeveloperProfileIdsWithLLM,
    developerProfiles.addTempDeveloperProfile,
    projects.add,
    projects.hasCurrentUserAccess,
    projects.delete,
    projects.getAll,
    projects.updateDescription,
    projects.updateProjectData,
    developerProfiles.addDeveloperProfile,
    developerProfiles.createDeveloperProfile,
    developerProfiles.delete,
    developerProfiles.getAllById,
    developerProfiles.getDeveloperById,
    developerProfiles.getDeveloperProfileByIdentityId,
    developerProfiles.getAll,
    developerProfiles.getCurrentUsers,
    developerProfiles.updateMissingSlugs,
    developerProfiles.getHighlightedDeveloperProfileIds,
    assignments.getAssignmentsByCohortId,
    assignments.getAverageScoresByIdentityId,
    assignments.getAllAverageScoresByIdentityId,
    assignments.getAssignmentBySlug,
  ]),
  core: new Set([
    developerProfiles.getAllEducations,
    developerProfiles.getAllLanguages,
    developerProfiles.getAllSkills,
    developerProfiles.getBackgroundByDeveloperProfileId,
    developerProfiles.updateBackground,
    developerProfiles.searchDeveloperProfileIds,
    developerProfiles.searchDeveloperProfileIdsWithLLM,
    developerProfiles.deleteBackgroundById,
    developerProfiles.addTempDeveloperProfile,
    developerProfiles.getHighlightedDeveloperProfileIds,
    projects.updateDescription,
    projects.updateProjectData,
    projects.hasCurrentUserAccess,
    projects.getAll,
    projects.deleteProjectsByDeveloperProfileId,
    developerProfiles.addDeveloperProfile,
    developerProfiles.createDeveloperProfile,
    developerProfiles.delete,
    developerProfiles.getAllById,
    developerProfiles.getDeveloperById,
    developerProfiles.getAll,
    developerProfiles.deleteByIdentityId,
    assignments.getAssignmentsByCohort,
    assignments.getAssignmentsByCohortId,
    assignments.getAssignmentById,
    assignments.createAssignment,
    assignments.deleteAssignmentScoreById,
    assignments.getAverageScoresByIdentityId,
    assignments.getAllAverageScoresByIdentityId,
    assignments.getAssignmentBySlug,
    cohorts.getAllUnassignedDevelopers,
    cohorts.addDeveloperToCohort,
    cohorts.deleteCohortIdentity,
  ]),
} as const;

export const rolesViewPermissions = {
  admin: new Set([
    projectPermissions.edit,
    MenuPermissions.instructorsDashboard,
    MenuPermissions.admin,
    MenuPermissions.hamburgerMenu,
    assignmentPermissions.score,
  ]),
  core: new Set([
    MenuPermissions.admin,
    MenuPermissions.instructorsDashboard,
    MenuPermissions.hamburgerMenu,
    assignmentPermissions.score,
  ]),
  developer: new Set([
    projectPermissions.edit,
    MenuPermissions.profile,
    MenuPermissions.hamburgerMenu,
  ]),
  guest: new Set([]),
} as const;
