name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - db-migration
  workflow_dispatch:
    inputs:
      action:
        description: "Choose the action: create or rename table"
        required: true
        default: "create"

jobs:
  apply_migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable for action
        run: echo "ACTION=${{ github.event.inputs.action }}" >> $GITHUB_ENV

      - name: Generate migrations
        run: |
          if [ "$ACTION" == "create" ]; then
            echo "Creating table..."
            drizzle-kit generate --create
          elif [ "$ACTION" == "rename" ]; then
            echo "Renaming table..."
            drizzle-kit generate --rename
          else
            echo "Invalid action"
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies & tooling
        run: |
          npm install
          npm install -g drizzle-orm drizzle-kit pg
      - name: Apply migrations
        run: |
          drizzle-kit generate
          drizzle-kit migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
  # Deploy-Production:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install Vercel CLI
  #       run: npm install --global vercel@latest
  #     - name: Pull Vercel Environment Information
  #       run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
  #     - name: Build Project Artifacts
  #       run: vercel build  --prod --token=${{ secrets.VERCEL_TOKEN }}
  #     - name: Deploy Project Artifacts to Vercel
  #       run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
